# Array Properties and Operations

In [2]:
import numpy as np
arr_1d = np.array([1,2,3])
arr_2d = np.array([[10,20,30],
                [40,50,60]])
arr_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [3]:
arr = np.array([[10,20,30],
                [40,50,60]])
print(arr.size)

6


In [3]:
arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr_2d.shape)   # give no. of rows and column

(2, 3)


#### .dtype -> data type of element

In [5]:
arr = np.array([1,2,3.9,4,5])
print(arr.dtype)

float64


#### Datatype conversion of array element
#### array.astype(newtype)

In [6]:
arr = np.array([1.2,2.8,3.9])
print(arr.dtype)
int_arr = arr.astype(int)

print(int_arr)
print(int_arr.dtype)

float64
[1 2 3]
int64


### Mathematical Operation on all Array elements

In [9]:
arr = np.array([10,20,30])

print(arr + 5)
print(arr * 2)
print(arr ** 2)

[15 25 35]
[20 40 60]
[100 400 900]


### Aggregation Functions
#### np.sum(array) -> add all
#### np.mean(array) -> calculate average
#### min(array) -> min
#### max(array) -> max
#### np.std(array) -> standard deviation
#### np.var(array) -> variance

In [11]:
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

150
30.0
10
50
14.142135623730951
200.0
