### Array Modifications
##### np.insert(array, index, value, axis = None)
##### axis = 0 -> row-wise
##### axis = 1 -> column-wise

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr = np.insert(arr, 2, 100, axis = 0)
print(new_arr)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [5]:
arr_2d = np.array([[1,2],[3,4]])
print(arr_2d)
new_arr_2d = np.insert(arr_2d,1, [5,6], axis = 1)
print(new_arr_2d)

[[1 2]
 [3 4]]
[[1 5 2]
 [3 6 4]]


 #### Append
 

In [7]:
arr = np.array([10,20,30])
new_arr = np.append(arr, [40,50,60])
print(new_arr)

[10 20 30 40 50 60]


#### Concatenate
##### np.concatenate((array1, array2),axis)
##### axis = 0 -> vertical stacking
##### axis = 1 -> horizontal stacking

In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new_arr = np.concatenate((arr1,arr2))
print(new_arr)

[1 2 3 4 5 6]


#### np.delete(array, index, axis = None)
##### flatten array

In [14]:
arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr = np.delete(arr,0)
print(new_arr)

[10 20 30 40 50 60]
[20 30 40 50 60]


In [16]:
arr_2d = np.array([[1,2,3],[4,5,6]])
new_arr_2d = np.delete(arr_2d,0,axis = 1)
print(new_arr_2d)

[[2 3]
 [5 6]]


### Stacking and Spliting
##### vstack() row wise
##### hstack() column wise

In [18]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.hstack((arr1,arr2)))

[1 2 3 4 5 6]


#### np.split() -> equal parts
#### np.hsplit()
#### np.vsplit() -> work with more than two dimension

In [25]:
arr = np.array([10,20,30,40,50,60])
print(arr)
# print(np.split(arr, 2))
print(np.hsplit(arr,2))

[10 20 30 40 50 60]
[array([10, 20, 30]), array([40, 50, 60])]
