## Broadcasting
#### matrix addition will be faster with broadcasting and for example convert 1d to 2d array for 

In [1]:
import numpy as np 
prices = np.array([100,200,300])
discount = 10

final_prices = prices - (prices * discount/100)

print(final_prices)

[ 90. 180. 270.]


### Vectorization
##### traditional loop method is slow so we use vectorization

In [2]:
list1 = [1,2,3]
list2 = [4,5,6]

result = [x+y for x,y in zip(list1, list2)]
print(result)

[5, 7, 9]


##### above one is slow python loop in DS and ML we need fast operation so we do this vectorization :-

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
multiplied = arr1*3
print(multiplied)
print(result)

[3 6 9]
[5 7 9]
