### indexing and slicing
##### array[start:stop:step]

##### arr[start:end], start to end -1
##### negative step, -1 reverse

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50,60])
print(arr[1:5])
print(arr[:4])
print(arr[::2])
print(arr[::-1])

[20 30 40 50]
[10 20 30 40]
[10 30 50]
[60 50 40 30 20 10]


### Fancy Indexing 
##### selecting multiple elements at once

In [2]:
print(arr[[0,2,4]])

[10 30 50]
