# Numpy Installation



In [2]:
!pip install numpy

### Comparing List with Numpy Array

In [11]:
python_list = [1,2,3,4,5]
print(python_list)

import numpy as np   # importing here but this np can be used in further below cell too..
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [6]:
ar_1d = np.array([10,20,30,40,50])

print(ar_1d)

[10 20 30 40 50]


### Creating 2D Array :-

In [12]:
arr_2D = np.array([[1,2,3],  #also this is a matrix
                  [4,5,6],
                  [7,8,9]])
print(arr_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Array creating with default values



In [16]:
zeroes_array = np.zeros(3)
print(zeroes_array)

zeroes_array = np.ones((2,3))
print(zeroes_array)

filled_Array = np.full((2,2),7)
print(filled_Array)

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]


### Creating sequence of number in numpy 
#### arange()                  arange(start,stop,step)

In [17]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


### Creating identity matrices
#### eye(size)

In [18]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
import os
os.getcwd()

'D:\\Anaconda'