### Reshaping of Array
#### Reshaping doesnt create copy it just returns a view

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
reshaped_Arr = arr.reshape(2,3)
print(reshaped_Arr)

[[1 2 3]
 [4 5 6]]


### Flattening array
#### converts multi-dimensional array into 1D array
##### .ravel -> returns view and .flatten() -> return copy

In [4]:
arr_2D = np.array([[1,2,3],[4,5,6]])
print(arr_2D.ravel())
print(arr_2D.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]
